/**
 * models/InterviewReport.ts
 *
 * Mongoose schema for the InterviewReport collection.
 *
 * Each report belongs to one user and stores everything generated by the AI:
 * match score, questions, skill gaps, and a preparation plan.
 *
 * We also store the original resume text, job description, and self-description
 * so the ATS resume generator can re-use them without the user re-uploading.
 *
 * Sub-schemas use `{ _id: false }` because these are embedded value objects —
 * they don't need their own IDs and the extra ObjectIds would waste space.
 */

import mongoose, { Schema } from "mongoose"

// ─── Sub-schemas ──────────────────────────────────────────────────────────────

const interviewQuestionSchema = new Schema(
  {
    question: String,
    intention: String,  // What the interviewer is really testing for
    answer: String,     // Guide on how the candidate should respond
  },
  { _id: false }
)

const skillGapSchema = new Schema(
  {
    skill: String,
    severity: {
      type: String,
      enum: ["low", "medium", "high"],
    },
  },
  { _id: false }
)

const preparationDaySchema = new Schema(
  {
    day: Number,
    focus: String,    // The theme or topic for this day
    tasks: [String],  // Specific, actionable study tasks
  },
  { _id: false }
)

// ─── Main schema ──────────────────────────────────────────────────────────────

const interviewReportSchema = new Schema(
  {
    // The user who owns this report — used for ownership checks in every query
    user: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,  // We always query by user, so index this for performance
    },

    // AI-generated summary
    title: { type: String, required: true },
    matchScore: { type: Number, min: 0, max: 100 },

    // Source content — stored so ATS resume can be regenerated without re-upload
    resume: String,
    jobDescription: String,
    selfDescription: String,

    // AI-generated report content
    technicalQuestions: [interviewQuestionSchema],
    behavioralQuestions: [interviewQuestionSchema],
    skillGaps: [skillGapSchema],
    preparationPlan: [preparationDaySchema],
  },
  {
    // Automatically adds createdAt and updatedAt
    timestamps: true,
  }
)

const InterviewReportModel =
  mongoose.models.InterviewReport ||
  mongoose.model("InterviewReport", interviewReportSchema)

export default InterviewReportModel